### ISSUE TITLE
Render callback must implement TrustedCallbackInterface

### ISSUE THREAD

**Issue by spncr** [thinkshout/bene_media#33]
I've got a site crashing in `Content > Media`, but only if you try to edit a video. On this site all videos are Youtube embeds.

The error references this 8.8 feature:
https://www.drupal.org/node/2966725

It looks like the MediaForm class needs to `implement TrustedCallbackInterface` which requires a new function:
```
  /**
   * {@inheritdoc}
   */

  public static function trustedCallbacks() {
    return ['renderPreview'];
  }

  ```

**Comment by mariacha** [comment]
Closed via https://github.com/thinkshout/bene_media/pull/34
